/** Suggested values for Company Focus filter (multi-select + custom). */
export const COMPANY_FOCUS_OPTIONS = [
  "B2B SaaS",
  "B2C",
  "AI / Machine Learning",
  "Fintech",
  "E-commerce",
  "Healthcare / Healthtech",
  "Edtech",
  "Deep Tech",
  "Developer Tools",
  "Enterprise Software",
  "Consumer Apps",
  "Cybersecurity",
  "Cloud Infrastructure",
  "Data & Analytics",
  "Gaming",
  "Marketplace",
  "Social Media",
  "IoT",
  "Logistics / Supply Chain",
  "HR Tech",
  "AI infrastructure",
] as const;
